chain="polygon-amoy"
blockchain-service-url="https://polygon-amoy.g.alchemy.com/v2/ZfoJ68KxzQprncNJWWhTBzEDP95H6U7M"
clandestine-port="48726"
db-password="1234"
dns-servers="1.1.1.1,139.144.68.241,139.144.68.242,208.67.222.222,1.0.0.1,9.9.9.9"
gas-price="1"
ip="45.76.63.46"
log-level="trace"
neighborhood-mode="standard"
real-user="1000:1000:/home/ubuntu"
payment-thresholds="200000|300|1200|100000|21600|100000"
#neighbors=""
